service: aws-python-flask-dynamodb-api

frameworkVersion: "3"

custom:
  tableName: "academic-records-table-v2-${sls:stage}"
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::Join:
                - ""
                - - Fn::GetAtt: [UsersTable, Arn]
                  - "/index/*"
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: student_id
            AttributeType: S
          - AttributeName: course
            AttributeType: S
          - AttributeName: year
            AttributeType: S
        KeySchema:
          - AttributeName: student_id
            KeyType: HASH
          - AttributeName: course
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: course-year-index
            KeySchema:
              - AttributeName: course
                KeyType: HASH
              - AttributeName: year
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 10
              WriteCapacityUnits: 10
        LocalSecondaryIndexes:
          - IndexName: year-index
            KeySchema:
              - AttributeName: student_id
                KeyType: HASH
              - AttributeName: year
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: ${self:custom.tableName}
